on: 
  push:
    branches:
    - main
    paths:
    - 'research-project-main-report.qmd'  
name: Check Repo
jobs:
  check-rmd:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Check qmd Rendering
      run:  Rscript -e "quarto::quarto_render('research-project-main-report.qmd')"
